schedules:
- cron: "*/5 * * * *"
  displayName: Every 5 minutes
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    https://api.github.com/repos/kenbehren/exposure-locations/actions/workflows/flat.yaml/dispatches \
    -d '{"ref":"ref"}'
  displayName: 'Trigger workflow'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)

